chore(deps): bump multiple types packages (#1053)
Bump a small number of `@types/` npm packages.

This should address CI failures:

    [2021/08/03 10:07:50.109] > tsc -p tsconfig.json
    [2021/08/03 10:07:55.031] ../../node_modules/@types/express-serve-static-core/index.d.ts(504,18): error TS2430: Interface 'Response<ResBody, StatusCode>' incorrectly extends interface 'ServerResponse'.
    [2021/08/03 10:07:55.031]   Types of property 'req' are incompatible.
    [2021/08/03 10:07:55.031]     Type 'Request<ParamsDictionary, any, any, ParsedQs> | undefined' is not assignable to type 'IncomingMessage'.
    [2021/08/03 10:07:55.031]       Type 'undefined' is not assignable to type 'IncomingMessage'.

I’m not sure why those failures don’t show up in our waterfall builds,
or what exactly introduced them, but they appear in both PR and
Node.js driver integration builds at least:

- https://evergreen.mongodb.com/task/mongosh_linux_compile_ts_patch_fb1691775754ab5b9018acdb4831b423ee3d77e6_61041cb00305b97fe6c5119d_21_07_30_15_37_21
- https://evergreen.mongodb.com/task/mongo_node_driver_mongosh_integration_tests_run_mongosh_integration_tests_b42a1b417e8a4e222000336b0fe9e94053d30d98_21_07_30_17_03_33